# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_header', models.CharField(max_length=100, verbose_name='Заголовок новости')),
                ('news_body', models.CharField(max_length=200, verbose_name='Новость')),
                ('public_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата_создания')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новость',
            },
        ),
        migrations.CreateModel(
            name='PastResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_number', models.PositiveIntegerField()),
                ('second_number', models.PositiveIntegerField()),
                ('public_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name_plural': 'Предыдущие результаты',
                'verbose_name': 'Предыдущий результаты',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_rec', models.DateTimeField(verbose_name='По')),
                ('rec', models.CharField(choices=[('Покупать', 'Покупка'), ('Продавать', 'Продажа')], default='Покупать', max_length=100, verbose_name='Сигнал')),
            ],
            options={
                'verbose_name_plural': 'Сигналов',
                'verbose_name': 'Сигнал',
            },
        ),
    ]
