# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbersignal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastresults',
            options={'verbose_name': 'Предыдущий результат', 'verbose_name_plural': 'Предыдущие результаты'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name': 'Сигнал', 'verbose_name_plural': 'Сигналы'},
        ),
        migrations.AlterField(
            model_name='news',
            name='public_date',
            field=models.DateTimeField(verbose_name='Дата_создания'),
        ),
        migrations.AlterField(
            model_name='pastresults',
            name='public_date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
