# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbersignal', '0002_auto_20160409_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastresults',
            name='public_date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
