# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbersignal', '0003_auto_20160409_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_date',
            field=models.DateField(verbose_name='Дата_создания'),
        ),
    ]
