# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbersignal', '0006_auto_20160409_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='rec',
            field=models.CharField(choices=[('True', 'Покупка'), ('False', 'Продажа')], default='True', max_length=100, verbose_name='Сигнал'),
        ),
    ]
