# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbersignal', '0007_auto_20160409_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='rec',
            field=models.CharField(choices=[(0, 'Покупка'), (1, 'Продажа')], default=0, max_length=100, verbose_name='Сигнал'),
        ),
    ]
