# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sbersignal', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 11, 18, 12, 672767, tzinfo=utc)),
        ),
    ]
