# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbersignal', '0013_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='phone',
            field=models.CharField(max_length=17),
        ),
    ]
