# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbersignal', '0014_auto_20160418_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
